config/routes.rb
Rails.application.routes.draw do
  resources :ripples

end

app/models/ripple.rb
class Ripple < ActiveRecord::Base

	validates :name, :message, presence: true
	
	before_destroy :prevent_destroy
	
	def prevent_destroy
		false
	end
	
	before_update :prevent_update
	
	def prevent_update
		false
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show, :edit, :update, :destroy]

  # GET /ripples
  # GET /ripples.json
  def index
    @ripples = Ripple.all
    @ripples.reverse_order!
  end

  # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  # GET /ripples/1/edit
  def edit
	redirect_to action: "index"
  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)

    respond_to do |format|
      if @ripple.save
        format.html { redirect_to action: "index", notice: 'Ripple was successfully created.' }
        format.json { render :show, status: :created, location: @ripple }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ripples/1
  # PATCH/PUT /ripples/1.json
  def update
    respond_to do |format|
      if @ripple.update(ripple_params)
        format.html { redirect_to @ripple, notice: 'Ripple was successfully updated.' }
        format.json { render :show, status: :ok, location: @ripple }
      else
        format.html { render :edit }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ripples/1
  # DELETE /ripples/1.json
  def destroy
    @ripple.destroy
    respond_to do |format|
      format.html { redirect_to ripples_url, notice: 'Ripple deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:name, :url, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consciousmess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="sitebanner">
<h1>CONSCIOUS/mess</h1>
<h2>...a stream of anonymous online ramblings</h2>
</div>

<%= yield %>

</body>
</html>

app/views/ripples/_form.html.erb
<%= form_for(@ripple) do |f| %>
  <% if @ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ripple.errors.count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% @ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message, rows: 10, cols: 50 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ripples/edit.html.erb
<h1>Editing Ripple</h1>

<%= render 'form' %>

<%= link_to 'Show', @ripple %> |
<%= link_to 'Back', ripples_path %>

app/views/ripples/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ripples.each do |ripple| %>
      <tr>
        <td><%= link_to_unless ripple.url == "", ripple.name, ripple.url %></td>
        <td><%= ripple.message %></td>
        <td><%= ripple.created_at %></td>
        <td><%= link_to 'Show', ripple %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Newest', '/ripples' %>
<%= link_to 'Prev 10 Ripples', '/ripples' %>
<%= link_to 'Next 10 Ripples', '/ripples' %>
<%= link_to 'New Ripple', new_ripple_path %>

app/views/ripples/new.html.erb
<h1>New Ripple</h1>

<%= render 'form' %>

<%= link_to 'Back', ripples_path %>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show">

  <p>
    <strong><%= @ripple.name %> said:</strong>
    <br>
    <br>
  </p>

  <p id="indent">
    <%= @ripple.message %>
  </p>

</div>

<%= link_to 'Back', ripples_path %>